// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDliiHk2ZUqVLDd7bmFCHZPcX7j6WZyWbw',
    appId: '1:425864386246:web:af82b47fa3ae0aa74729c7',
    messagingSenderId: '425864386246',
    projectId: 'ranobelib-0',
    authDomain: 'ranobelib-0.firebaseapp.com',
    databaseURL: 'https://ranobelib-0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ranobelib-0.appspot.com',
    measurementId: 'G-HMTCMSH8RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB2Gsj_fcMYskkWfO2wVyk7nlMx5_Op8c',
    appId: '1:425864386246:android:9096acbfab79a7e34729c7',
    messagingSenderId: '425864386246',
    projectId: 'ranobelib-0',
    databaseURL: 'https://ranobelib-0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ranobelib-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4f98QdqH63wdhIA0jKYu1-UBxD_Cjrf4',
    appId: '1:425864386246:ios:f1dc0cf91f861a1a4729c7',
    messagingSenderId: '425864386246',
    projectId: 'ranobelib-0',
    databaseURL: 'https://ranobelib-0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ranobelib-0.appspot.com',
    iosBundleId: 'com.example.battlecat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4f98QdqH63wdhIA0jKYu1-UBxD_Cjrf4',
    appId: '1:425864386246:ios:f1dc0cf91f861a1a4729c7',
    messagingSenderId: '425864386246',
    projectId: 'ranobelib-0',
    databaseURL: 'https://ranobelib-0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ranobelib-0.appspot.com',
    iosBundleId: 'com.example.battlecat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDliiHk2ZUqVLDd7bmFCHZPcX7j6WZyWbw',
    appId: '1:425864386246:web:6e978ce6890af3984729c7',
    messagingSenderId: '425864386246',
    projectId: 'ranobelib-0',
    authDomain: 'ranobelib-0.firebaseapp.com',
    databaseURL: 'https://ranobelib-0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ranobelib-0.appspot.com',
    measurementId: 'G-RQN4QYWPV4',
  );
}
