// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChO14R1Whcxmfjq2USHYwQcR8lEEtZmWQ',
    appId: '1:874211422364:web:79bb8bfdbc0d802e90bd59',
    messagingSenderId: '874211422364',
    projectId: 'azur-lane-87bfe',
    authDomain: 'azur-lane-87bfe.firebaseapp.com',
    databaseURL: 'https://azur-lane-87bfe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'azur-lane-87bfe.appspot.com',
    measurementId: 'G-PHPZPGTTBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCsyOkCXDTykhdySsMHH3OmUWTlHheDKA',
    appId: '1:874211422364:android:8ca7b9a536730cac90bd59',
    messagingSenderId: '874211422364',
    projectId: 'azur-lane-87bfe',
    databaseURL: 'https://azur-lane-87bfe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'azur-lane-87bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3JwUbNS_SXZVFSJ3jyZtUoUuRUDwR-o',
    appId: '1:874211422364:ios:c56f8e776e8d4c7790bd59',
    messagingSenderId: '874211422364',
    projectId: 'azur-lane-87bfe',
    databaseURL: 'https://azur-lane-87bfe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'azur-lane-87bfe.appspot.com',
    iosBundleId: 'com.example.azurlane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ3JwUbNS_SXZVFSJ3jyZtUoUuRUDwR-o',
    appId: '1:874211422364:ios:c56f8e776e8d4c7790bd59',
    messagingSenderId: '874211422364',
    projectId: 'azur-lane-87bfe',
    databaseURL: 'https://azur-lane-87bfe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'azur-lane-87bfe.appspot.com',
    iosBundleId: 'com.example.azurlane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChO14R1Whcxmfjq2USHYwQcR8lEEtZmWQ',
    appId: '1:874211422364:web:58d4807e852cd75590bd59',
    messagingSenderId: '874211422364',
    projectId: 'azur-lane-87bfe',
    authDomain: 'azur-lane-87bfe.firebaseapp.com',
    databaseURL: 'https://azur-lane-87bfe-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'azur-lane-87bfe.appspot.com',
    measurementId: 'G-0RFKKFJ1X3',
  );
}
