// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGpzhEocBDrpI7ji_BEBDFfHJuEtBsV-A',
    appId: '1:1050690965435:web:1ff02a74fb333fd5053e9e',
    messagingSenderId: '1050690965435',
    projectId: 'cities-99401',
    authDomain: 'cities-99401.firebaseapp.com',
    databaseURL: 'https://cities-99401-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cities-99401.appspot.com',
    measurementId: 'G-PFR71E3LJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8rEL1b1oWVCEvesh-aDFFf7YnlovIzK8',
    appId: '1:1050690965435:android:2e3dce9b183695e3053e9e',
    messagingSenderId: '1050690965435',
    projectId: 'cities-99401',
    databaseURL: 'https://cities-99401-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cities-99401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxsblKvMYNhMD0FBoPelf-2-mGQsmpQDI',
    appId: '1:1050690965435:ios:3104dce69b45372a053e9e',
    messagingSenderId: '1050690965435',
    projectId: 'cities-99401',
    databaseURL: 'https://cities-99401-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cities-99401.appspot.com',
    iosBundleId: 'com.example.cities',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxsblKvMYNhMD0FBoPelf-2-mGQsmpQDI',
    appId: '1:1050690965435:ios:3104dce69b45372a053e9e',
    messagingSenderId: '1050690965435',
    projectId: 'cities-99401',
    databaseURL: 'https://cities-99401-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cities-99401.appspot.com',
    iosBundleId: 'com.example.cities',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGpzhEocBDrpI7ji_BEBDFfHJuEtBsV-A',
    appId: '1:1050690965435:web:84b9317b0bc2400a053e9e',
    messagingSenderId: '1050690965435',
    projectId: 'cities-99401',
    authDomain: 'cities-99401.firebaseapp.com',
    databaseURL: 'https://cities-99401-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cities-99401.appspot.com',
    measurementId: 'G-QC6WNRFH85',
  );
}
