// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdfuY7hRJGgKCWeOlab06SMB3oB65hta4',
    appId: '1:531545069895:web:341db9efb1d65661215462',
    messagingSenderId: '531545069895',
    projectId: 'overwatch-95808',
    authDomain: 'overwatch-95808.firebaseapp.com',
    databaseURL: 'https://overwatch-95808-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'overwatch-95808.appspot.com',
    measurementId: 'G-NBT9XN0BSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo6Ey7vhV_cwOYu0iiboXAb9EbAb-qyrU',
    appId: '1:531545069895:android:e7e654dd9ef01679215462',
    messagingSenderId: '531545069895',
    projectId: 'overwatch-95808',
    databaseURL: 'https://overwatch-95808-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'overwatch-95808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUd5kKsuLYUOxymlt4LJySAe8F4MHolmA',
    appId: '1:531545069895:ios:06e56dcba23542f4215462',
    messagingSenderId: '531545069895',
    projectId: 'overwatch-95808',
    databaseURL: 'https://overwatch-95808-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'overwatch-95808.appspot.com',
    iosBundleId: 'com.example.overwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUd5kKsuLYUOxymlt4LJySAe8F4MHolmA',
    appId: '1:531545069895:ios:06e56dcba23542f4215462',
    messagingSenderId: '531545069895',
    projectId: 'overwatch-95808',
    databaseURL: 'https://overwatch-95808-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'overwatch-95808.appspot.com',
    iosBundleId: 'com.example.overwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdfuY7hRJGgKCWeOlab06SMB3oB65hta4',
    appId: '1:531545069895:web:e8e07bde4de1ee29215462',
    messagingSenderId: '531545069895',
    projectId: 'overwatch-95808',
    authDomain: 'overwatch-95808.firebaseapp.com',
    databaseURL: 'https://overwatch-95808-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'overwatch-95808.appspot.com',
    measurementId: 'G-S5MV22TNG6',
  );
}
